"""empty message

Revision ID: 780a2fec47c3
Revises: 8f6e19f024f2
Create Date: 2020-08-30 18:46:52.719222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780a2fec47c3'
down_revision = '8f6e19f024f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('other_description')

    # ### end Alembic commands ###
